services:
  - type: web
    name: devsync-ai
    env: python
    runtime: python-3.12
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --no-cache-dir --only-binary=:all: --prefer-binary --no-build-isolation -r requirements.txt"
    startCommand: "uvicorn devsync_ai.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: GITHUB_REPOSITORY
        value: asakohayase/kiro-devsync-ai
      - key: SUPABASE_URL
        value: https://pbkmbvvqjjglvuoilbwu.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBia21idnZxampnbHZ1b2lsYnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzQ3NzcsImV4cCI6MjA2OTkxMDc3N30.3Sd7IFUDbJ78J4tSfceBgl2SLHV9_Pois3sgAkmOqfQ
      - key: REDIS_URL
        value: redis://localhost:6379