environment: development
last_updated: '2025-08-15T01:49:14.892549'
message_templates:
  alert:
    custom_fields:
      escalation_enabled: true
      show_affected_systems: true
      show_severity: true
    enabled: true
    template_type: alert
  jira_update:
    custom_fields:
      highlight_blockers: true
      show_epic_link: true
      show_story_points: true
    enabled: true
    template_type: jira_update
  pr_update:
    custom_fields:
      highlight_conflicts: true
      show_ci_status: true
      show_diff_stats: true
    enabled: true
    template_type: pr_update
  standup:
    custom_fields:
      show_progress_bars: true
      show_team_health: true
      show_velocity: true
    enabled: true
    template_type: standup
migration_version: 2
team_settings:
  content_preferences:
    max_description_length: 500
    show_ci_status: true
    show_file_changes: true
    show_technical_details: true
  custom_fields:
    header_style: standard
    logo_emoji: ':gear:'
  default_formatting: rich
  interactive_settings:
    enable_threading: true
    interactive_mode: true
    show_action_buttons: true
  team_id: demo_team
  team_name: Demo_Team Team
  timezone: UTC
  visual_styling:
    brand_color: '#1f77b4'
    compact_mode: false
    custom_emojis:
      error: "\u274C"
      success: "\u2705"
      warning: "\u26A0\uFE0F"
    emoji_style: standard
    error_color: '#d62728'
    message_density: detailed
    secondary_color: '#ff7f0e'
    show_avatars: true
    show_timestamps: true
    success_color: '#2ca02c'
    warning_color: '#ff7f0e'
version: 1.0.0
