# DevSync AI Template Configuration
# Environment-specific template settings

environment: "production"

# Feature flags for template variations
feature_flags:
  enhanced_pr_templates: true
  security_alerts: true
  ab_testing: true
  template_caching: true
  metrics_collection: true

# Cache settings
cache:
  enabled: true
  max_size: 1000
  ttl: 3600  # 1 hour

# Template configurations
templates:
  # Standup templates
  standup:
    - name: "default_standup"
      version: "stable"
      enabled: true
      weight: 80
      metadata:
        description: "Standard daily standup template"
        author: "DevSync Team"
    
    - name: "enhanced_standup"
      version: "beta"
      enabled: true
      weight: 20
      feature_flags: ["enhanced_pr_templates"]
      metadata:
        description: "Enhanced standup with additional metrics"
        author: "DevSync Team"

  # PR update templates
  pr_update:
    - name: "default_pr"
      version: "stable"
      enabled: true
      weight: 70
      metadata:
        description: "Standard PR update template"
    
    - name: "enhanced_pr"
      version: "beta"
      enabled: true
      weight: 30
      feature_flags: ["enhanced_pr_templates"]
      metadata:
        description: "Enhanced PR template with additional context"

  # JIRA update templates
  jira_update:
    - name: "default_jira"
      version: "stable"
      enabled: true
      weight: 100
      metadata:
        description: "Standard JIRA update template"

  # Alert templates
  alert:
    - name: "default_alert"
      version: "stable"
      enabled: true
      weight: 60
      metadata:
        description: "Standard alert template"
    
    - name: "enhanced_alert"
      version: "beta"
      enabled: true
      weight: 40
      feature_flags: ["security_alerts"]
      metadata:
        description: "Enhanced alert template with security focus"

# Environment-specific overrides
environments:
  development:
    feature_flags:
      enhanced_pr_templates: true
      security_alerts: true
      ab_testing: false
      template_caching: false
    
    templates:
      alert:
        - name: "debug_alert"
          version: "experimental"
          enabled: true
          weight: 100
          environment: "development"

  staging:
    feature_flags:
      enhanced_pr_templates: true
      security_alerts: true
      ab_testing: true
      template_caching: true

  production:
    feature_flags:
      enhanced_pr_templates: false  # Disable experimental features
      security_alerts: true
      ab_testing: true
      template_caching: true

# A/B testing configuration
ab_testing:
  enabled: true
  user_assignment_persistence: true
  metrics_collection: true

# Performance monitoring
monitoring:
  enabled: true
  log_slow_renders: true
  slow_render_threshold: 1.0  # seconds
  collect_metrics: true
  metrics_retention: 86400  # 24 hours